--- #YAML:1.0
name:               Rose-DBx-Object-Cached-FastMmap
version:            0.05
abstract:           Module abstract (<= 44 characters) goes here
author:
    - Kevin C. McGrath (kmcgrath@baknet.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FastMmap:   0
    Rose::DB::Object:  0
    Test::Simple:      0.44
resources:
    repository:  https://github.com/kmcgrath/perl5-Rose-DBx-Object-Cached-FastMmap
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
